### ISSUE TITLE
Gerber Files

### ISSUE THREAD

**Issue by AxelAhlborn** [teuler/robotling2#2]
Hallo,
gibt es Gerber Files für die Platine ?
MfG Axel Ahlborn

**Comment by teuler** [comment]
Hallo Axel,
habe ich nun hinzugefügt. Ich habe sie aus Fritzing exportiert, ich habe sie allerdings noch nie ausprobiert - die Platinen habe ich bisher immer direkt aus der Fritzing-Datei herstellen lassen.
VGT

**Comment by teuler** [comment]
Falls irgenwelche Probleme mit den Gerber files auftreten wäre ich für einen Hinweis dankbar :-)

**Comment by AxelAhlborn** [comment]
Hallo, vielen Dank für die Gerber Files. Ich konnte heute das ZIP Archiv
ohne Probleme bei JLCPCB einchecken und bestellen. Somit gehe ich davon
aus, dass alles i.O. ist. Ich werde für das Projekt etwas brauchen, da der
Sommer kommt und so etwas eher für die kalte Jahreszeit ist.
MFG Axel Ahlborn

Thomas Euler ***@***.***> schrieb am Mo., 10. Apr. 2023,
11:15:

**Comment by HMSteve** [comment]
> Falls irgenwelche Probleme mit den Gerber files auftreten wäre ich für einen Hinweis dankbar :-)

Habe auf Basis der Gerber files bei JLC bestellt und gestern bestueckt, Platine sieht gut aus und der Robotling laeuft damit. Danke fuers Teilen🙂

**Comment by teuler** [comment]
Sehr schön - danke fürs Feedback
